### ISSUE TITLE
Convert Project Into A Step-by-Step Tutorial

### ISSUE THREAD

**Issue by nhubbard** [nhubbard/compiler-from-scratch#1]
#### Summary
Create a compiler from scratch project using [Leg](https://github.com/snaptoken/leg). Big, huge process.

#### Tasks/Steps to Convert
- [ ] Introduction to the Journey
- [ ] Introduction to Lexical Scanning
- [ ] Introduction to Parsing
- [ ] Operator Precedence
- [ ] An Actual Compiler
- [ ] Statements
- [ ] Variables
- [ ] Comparison Operators
- [ ] If Statements
- [ ] While Loops
- [ ] For Loops
- [ ] Functions, part 1
- [ ] Types, part 1
- [ ] Functions, part 2
- [ ] Generating ARM Assembly Code
- [ ] Pointers, part 1
- [ ] Declaring Global Variables Properly
- [ ] Better Type Checking and Pointer Offsets
- [ ] Lvalues and Rvalues Revisited
- [ ] Arrays, part 1
- [ ] Character and String Literals
- [ ] More Operators
- [ ] Design Ideas for Local Variables and Function Calls
- [ ] Local Variables
- [ ] Function Parameters
- [ ] Function Calls and Arguments
- [ ] Function Prototypes
- [ ] Regression Testing and a Nice Surprise
- [ ] Adding More Run-time Flags
- [ ] A Bit of Refactoring
- [ ] Designing Structs, Unions and Enums
- [ ] Implementing Structs, Part 1
- [ ] Accessing Members in a Struct
- [ ] Implementing Unions and Member Access
- [ ] Enums and Typedefs
- [ ] The C Pre-Processor
- [ ] `break` and `continue`
- [ ] Switch Statements
- [ ] Dangling Else and More
- [ ] Variable Initialisation, part 1
- [ ] Global Variable Initialisation
- [ ] Local Variable Initialisation
- [ ] Type Casting and NULL
- [ ] Bugfixes and More Operators
- [ ] Constant Folding
- [ ] Global Variable Declarations, revisited
- [ ] Void Function Parameters and Scanning Changes
- [ ] A Subset of `sizeof`
- [ ] A Subset of `static`
- [ ] The Ternary Operator
- [ ] Mopping Up, part 1
- [ ] Arrays, part 2
- [ ] Pointers, part 2
- [ ] Mopping Up, part 2
- [ ] Spilling Registers
- [ ] Lazy Evaluation
- [ ] Local Arrays
- [ ] Mopping Up, part 3
- [ ] Fixing Pointer Increments/Decrements
- [ ] Why Doesn't It Work, part 1
- [ ] Passing the Triple Test
- [ ] What's Next?
- [ ] Code Cleanup
